[package]
name = "grep"
version = "0.5.0"
authors = ["abderrahim amzaourou <abderrahim.amzaourou@gmail.com>"]
edition = "2021"

[dependencies]
jwalk = "0.6.0"
clap = "3.2.17"

[dev-dependencies]
pretty_assertions = "1.0.0"

[profile.release]
lto = true
strip = true
